  version: 2
  updates:
    - package-ecosystem: npm
      directory: /code/client
      schedule:
        interval: weekly
      commit-message:
        prefix: 'deps(client):'
      labels:
        - dependencies
    - package-ecosystem: npm
      directory: /code/server
      schedule:
        interval: weekly
      commit-message:
        prefix: 'deps(server):'
      labels:
        - dependencies
    - package-ecosystem: npm
      directory: /code/shared
      schedule:
        interval: weekly
      commit-message:
        prefix: 'deps(shared):'
      labels:
        - dependencies
    - package-ecosystem: github-actions
      directory: /
      schedule:
        interval: weekly
      commit-message:
        prefix: 'chore(deps):'
      labels:
        - dependencies