version: 'latest'
services:
  postgres-db:
    container_name: notespace-postgres-db
    build:
      context: .
      dockerfile: ./docker/Dockerfile-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
