FROM postgres

COPY sql/create_tables.sql /docker-entrypoint-initdb.d/1_create-schema.sql

COPY --chown=postgres:postgres ./docker/scripts/wait-for-postgres.sh /usr/local/bin/wait-for-postgres.sh
RUN chmod +x /usr/local/bin/wait-for-postgres.sh

EXPOSE 5432
