name: Validate client

'on':
  push:
    branches:
      - main
jobs:
  client:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        working-directory:
          - code/client

    runs-on: '${{ matrix.os }}'

    defaults:
      run:
        working-directory: '${{ matrix.working-directory }}'

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 'latest'

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: pnpm install

      - name: Test client
        run: pnpm test